apiVersion: eks.aws.upbound.io/v1beta1
kind: Cluster
metadata:
  annotations:
    meta.upbound.io/example-id: eks/v1beta1/cluster
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    region: us-west-1
    roleArnSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    vpcConfig:
    - subnetIds:
      - ${aws_subnet.example1.id}
      - ${aws_subnet.example2.id}

---

