/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

// Package apis contains Kubernetes API for the provider.
package apis

import (
	"k8s.io/apimachinery/pkg/runtime"

	v1beta1 "github.com/upbound/provider-aws/apis/autoscaling/v1beta1"
	v1beta1dynamodb "github.com/upbound/provider-aws/apis/dynamodb/v1beta1"
	v1beta1ec2 "github.com/upbound/provider-aws/apis/ec2/v1beta1"
	v1beta1ecr "github.com/upbound/provider-aws/apis/ecr/v1beta1"
	v1beta1ecrpublic "github.com/upbound/provider-aws/apis/ecrpublic/v1beta1"
	v1beta1eks "github.com/upbound/provider-aws/apis/eks/v1beta1"
	v1beta1elasticache "github.com/upbound/provider-aws/apis/elasticache/v1beta1"
	v1beta1elasticsearch "github.com/upbound/provider-aws/apis/elasticsearch/v1beta1"
	v1beta1iam "github.com/upbound/provider-aws/apis/iam/v1beta1"
	v1beta1kinesis "github.com/upbound/provider-aws/apis/kinesis/v1beta1"
	v1beta1kms "github.com/upbound/provider-aws/apis/kms/v1beta1"
	v1beta1opensearch "github.com/upbound/provider-aws/apis/opensearch/v1beta1"
	v1beta1rds "github.com/upbound/provider-aws/apis/rds/v1beta1"
	v1beta1s3 "github.com/upbound/provider-aws/apis/s3/v1beta1"
	v1beta1secretsmanager "github.com/upbound/provider-aws/apis/secretsmanager/v1beta1"
	v1alpha1 "github.com/upbound/provider-aws/apis/v1alpha1"
	v1beta1apis "github.com/upbound/provider-aws/apis/v1beta1"
)

func init() {
	// Register the types with the Scheme so the components can map objects to GroupVersionKinds and back
	AddToSchemes = append(AddToSchemes,
		v1beta1.SchemeBuilder.AddToScheme,
		v1beta1dynamodb.SchemeBuilder.AddToScheme,
		v1beta1ec2.SchemeBuilder.AddToScheme,
		v1beta1ecr.SchemeBuilder.AddToScheme,
		v1beta1ecrpublic.SchemeBuilder.AddToScheme,
		v1beta1eks.SchemeBuilder.AddToScheme,
		v1beta1elasticache.SchemeBuilder.AddToScheme,
		v1beta1elasticsearch.SchemeBuilder.AddToScheme,
		v1beta1iam.SchemeBuilder.AddToScheme,
		v1beta1kinesis.SchemeBuilder.AddToScheme,
		v1beta1kms.SchemeBuilder.AddToScheme,
		v1beta1opensearch.SchemeBuilder.AddToScheme,
		v1beta1rds.SchemeBuilder.AddToScheme,
		v1beta1s3.SchemeBuilder.AddToScheme,
		v1beta1secretsmanager.SchemeBuilder.AddToScheme,
		v1alpha1.SchemeBuilder.AddToScheme,
		v1beta1apis.SchemeBuilder.AddToScheme,
	)
}

// AddToSchemes may be used to add all resources defined in the project to a Scheme
var AddToSchemes runtime.SchemeBuilder

// AddToScheme adds all Resources to the Scheme
func AddToScheme(s *runtime.Scheme) error {
	return AddToSchemes.AddToScheme(s)
}
